### ISSUE TITLE
Regarding the configuration interface that appears in the latest version 8.0.0, the first step is to repeatedly restart and get stuck in the first step when confirming.

### ISSUE THREAD

**Issue by lyz0994** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#13] opened 2023-07-25 10:33 UTC
Hello,I would like to give you feedback on a question. After using the latest version 8.0 for a brand new installation, I entered the settings interface and then went black screen and restarted. Then I re-entered the configuration interface and restarted the first step again. I hope it can be repaired.

**Comment by balopez83** [comment] 2023-07-25 16:14
Hi @lyz0994 please provide more information. I am unable to duplicate your issue. 

Did you correctly create an installation USB? This repo only supports macOS installation USB's that are made the "official" way through macOS. Any installation made through sources like GibOS or through unofficial sources are not supported as they will not function with this repo. 

There is no configuration interface that is needed with this release. You must simply create an official installation USB installer on a GPT partitioned USB and then simply copy the EFI to that USB's EFI partition. Upon reboot it will just work so long as you turned off secure boot. 

Also please provide more information. Screenshots and model/type/specs of computer you are using will help me figure out what the issue is. This supports the all variations of the Surface Pro 4 and Surface Book Gen 1.

**Comment by balopez83** [comment] 2023-07-31 06:42
@lyz0994 I assume this issue has been resolved and so will be closing this item. If you still need assistance you can reopen this issue.

**Closed as completed by balopez83** 2023-07-31 06:42 UTC

**Comment by billabongbruno** [comment] 2023-08-02 07:26
> @lyz0994 I assume this issue has been resolved and so will be closing this item. If you still need assistance you can reopen this issue.

Hey there once again.

I noticed that after your 8.0.1 release, addressing this issue, your USB mapping has changed.
With Sonoma, the micro SD is no longer recognized with this mapping.
I will give the old mapping a go and see if it works and then report here.

**Comment by balopez83** [comment] 2023-10-20 23:28
@lyz0994 After re-reading your post. The issue is that you used the wrong config.plist. You need to use only the one that matches your computer specifically. If you accidentally use the wrong one it will cause reboots due to misconfigured graphics.
