### ISSUE TITLE
Want to add support for the surface connect interface

### ISSUE THREAD

**Issue by Sunburst0218** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#12] opened 2023-07-24 05:39 UTC
Because you want to use Microsoft's docking station, you need to use the surfaceconnect interface, that is, the charging interface. Hope to support, thank the author.

**Comment by balopez83** [comment] 2023-07-24 06:41
@Sunburst0218 I’m a little confused with your issue. The surface connect port should be active as it’s driven through the USB interface. Graphics is also driven through that port and should work as well. 

Are you unable to get your Surface dock working?

**Comment by Sunburst0218** [comment] 2023-07-26 06:24
Yeah, it doesn't work. I plugged in the USB port on the docking station and the MAC didn't respond.

**Comment by Sunburst0218** [comment] 2023-07-26 07:57
The surface dock only charges the surface, and when I tried to connect my mouse, it
![C7D05987-88CD-4036-BC62-200F044DB6F5](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/99610421/89bd794e-d6ae-4a98-8cf3-ee9a09c14a57)
 plugged in, but it didn't work
![3C870F8D-CD95-487D-AA54-370BCED19F67](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/99610421/b8854352-d228-4cf6-ab46-048cbafd5a05)

**Comment by balopez83** [comment] 2023-07-26 21:39
@Sunburst0218 

So it's likely the USB port that is needed by the dock has been shut off. Can you use the following tool in windows with your dock connected and at least one USB 2 and one USB 3 device plugged into the dock and send me the resulting kext?
[USB Toolbox](https://github.com/USBToolBox/tool)

I can then take the data in the kext to get the dock running in macOS

**Comment by Sunburst0218** [comment] 2023-07-27 01:16
[UTBMap.kext.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12178479/UTBMap.kext.zip)

**Comment by Sunburst0218** [comment] 2023-07-27 01:18
I plugged a wireless card and a disk into the suface dock, and then exported the kext through the software you sent me. The author will see if it works. Thank you.

**Comment by balopez83** [comment] 2023-07-27 06:31
So I looked at what you sent and it appears to be the same as what I already have. I am not sure your dock was detected properly assuming there is another deactivated "port". 

Can you Rename the kext you sent me to: "UTBMap-SP4.kext" without the quotes and save it in your EFI partition under /EFI/OC/kexts

You should back up the existing kext just in case you need to replace it. The only difference between your kext and mine is that it identifies each USB port as a different type (e.g. internal, USB 2, USB 3, etc.). I will need to look into this further and have some ideas as to why it might not be working though it may take some time if port labeling isn't the solution. 

Once you replace that kext with the one you generated let me know if your dock starts working. If so I will update the main repo. If not, I will look into some other solutions. It may take some time for me to resolve this though as I am swamped with work and personal stuff so will do my best as I have time.

**Comment by Sunburst0218** [comment] 2023-07-27 06:44
I followed your tutorial, replaced the files, and restarted the mac, and now my surface dock is working.

**Comment by Sunburst0218** [comment] 2023-07-27 06:46
I tested the USB port, and the wireless card and mouse attached to the surface dock worked fine, but I didn't test the network card and audio out and minidp ports

**Comment by Sunburst0218** [comment] 2023-07-27 06:54
![22B93C00-2570-47AB-B829-2F3E9F8E73A6](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/99610421/7fc60cef-49cc-4e94-858e-c453289b2e11)
I tested the other USB ports on the surface dock, and they all worked, but there was a new problem, and the USB port that came with the surface pro 4 didn't work.😢

**Comment by balopez83** [comment] 2023-07-27 20:21
@Sunburst0218 well I am glad we are making progress. 
Will you replace your config.plist with this one and tell me what happens? Be prepared for macOS to not work or boot. 
[config-SurfacePro4-i3&i5.plist.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12187864/config-SurfacePro4-i3.i5.plist.zip)

If you already set up iServices (e.g. iMessage) make sure you add your SMBIOS information before restarting otherwise you could break your iServices.

**Comment by Sunburst0218** [comment] 2023-07-29 00:25
OK, I'll try.

**Comment by Sunburst0218** [comment] 2023-07-29 08:53
I found an EFI. In this EFI, the USB interface of the surface dock connected to my sueface pro4 works normally, and the USB interface of the surface also works normally. I will send it to you for reference. Thanks to the author.

**Comment by Sunburst0218** [comment] 2023-07-29 08:56
[surface pro4 oc efi支持Ventura13.4.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12206714/surface.pro4.oc.efi.Ventura13.4.zip)

**Comment by balopez83** [comment] 2023-07-29 21:55
@Sunburst0218 So I went through that EFI and it's a bit of a mess. They have a kext to enable all USB ports above the 15 port limit which is only supposed to be active for initial mapping as it can cause issues with power management when left active. Plus they have the mapping kexts and they have a patched DSDT which is a big no no for OpenCore. I am not sure if this will work but try the linked kext below by just replacing the one in my release EFI and see if that works. I used some information pulled out of the patched USB map kext in the EFI you sent me though I suspect that it might not work but let's hope for the best. If not I will need to dig a little deeper to see if there is a better way.

[UTBMap-SP4.kext.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12208093/UTBMap-SP4.kext.zip)

**Comment by Sunburst0218** [comment] 2023-07-30 00:22
I'm sorry to tell you that I tried the EFI you sent me and my surface dock didn't respond.

**Comment by balopez83** [comment] 2023-07-30 01:52
Yeah I figured it wouldn't work @Sunburst0218 can you run that other EFI where it did work and open hackintool. There is a USB tab where you can export the detected usb configuration. Make sure to click the clean button first so it doesn't accidentally export old USB configuration information.

Please then zip and send all the files it exports

**Comment by Sunburst0218** [comment] 2023-07-30 01:58
Okay, hold on a second.

**Comment by Sunburst0218** [comment] 2023-07-30 01:58
[归档.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12208367/default.zip)

**Comment by balopez83** [comment] 2023-07-30 03:41
@Sunburst0218 Thank you. It looks like it is sending 15 ports which I know the SP4 doesn't have that much so some of them are fake or are placeholders. 

Can I get you to do the same thing again but this time test all ports on the SP4 and the dock with both a USB 3 and USB 2 device. Each time you do that a green bar should show in Hackintool indicating the port is active. Can you then delete any remaining ones that were not highlighted green and delete them by pressing the minus button. Once only green ones remain go ahead and re-export and send me that zip. 

Thanks for handling this for me. While I have an SP4, I don't have a dock available to me so am unable to do this troubleshooting. I think after this last one I will be able to isolate the correct port that we are missing to get that active.

**Comment by Sunburst0218** [comment] 2023-07-30 04:51
Okay, hold on a second.

**Comment by Sunburst0218** [comment] 2023-07-30 04:52
[归档.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12208539/default.zip)

**Comment by balopez83** [comment] 2023-07-30 07:35
@Sunburst0218 I think we are getting close now. Give this one a try and let me know if everything is working. If not I have another option to try as well. 
[UTBMap-SP4.kext.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12208698/UTBMap-SP4.kext.zip)

**Comment by Sunburst0218** [comment] 2023-07-30 11:53
Thanks to the author, my surface dock is already working! Thank you

**Comment by balopez83** [comment] 2023-07-31 06:34
@Sunburst0218 Glad to hear that it is working now. I will add the revised USB mapping to the next release.

**Comment by billabongbruno** [comment] 2023-08-02 08:01
> @Sunburst0218 Glad to hear that it is working now. I will add the revised USB mapping to the next release.

Hey there once again.

I noticed that after your 8.0.1 release, addressing this issue, your USB mapping has changed.
With Sonoma, the micro SD is no longer recognized with this mapping.
I will give the old mapping a go and see if it works and then report here.

**Comment by billabongbruno** [comment] 2023-08-02 08:02
@balopez83 :

Confirmed.
The new USB Mapping does indeed break MicroSD support (at least under Sonoma).

The previous iteration is working just fine.

**Comment by Sunburst0218** [comment] 2023-08-02 08:06
Do you want to reinsert the SD card and export the file again?

**Comment by billabongbruno** [comment] 2023-08-02 08:08
> 

I removed and inserted the SD card more than once.
(In the integrated microSD card reader).

It failed to drive it.

**Comment by balopez83** [comment] 2023-08-02 08:27
@Sunburst0218 yes; can you insert an sd card and re-export the files? Thank you for helping.

@billabongbruno thanks for the catch on this. Once I get the export I'll integrate it into the patch and get a new release out.

**Comment by billabongbruno** [comment] 2023-08-02 08:39
> @Sunburst0218 yes; can you insert an sd card and re-export the files? Thank you for helping.
> 
> @billabongbruno thanks for the catch on this. Once I get the export I'll integrate it into the patch and get a new release out.

No worries.
I happened to catch that solely because I am currently trying out Sonoma and transferred some stuff onto the microSD while under Windows, so that I could install it in macOS.
Once I booted macOS, I was confused as to why it was not showing up.

Before Sonoma installation, I took the liberty of updating to your 8.0.1 release and remembered that, hence my comment.
After I tried the 8.0.0 USB Mapping, it all worked great.

For now I'll remain in 8.0.0-USB-based release and once @Sunburst0218 provides the log file and you integrate it into your new release, I'll use that instead.

Once again, I can only thank you for the massive work you have had with this project so far.
Had it not been for you, the SP4 would not have reached this level of functionality under macOS, regardless of your sources and inspirations.

Thank you.


Best regards,
Bruno.

**Comment by Sunburst0218** [comment] 2023-08-02 08:51
Okay, I might need a little time now.

**Comment by billabongbruno** [comment] 2023-08-02 08:56
@balopez83 :

I just noticed something else.
I am unsure if it's on my end, a Sonoma issue, a IPTSDaemon issue or something else.

The stylus isn't working.

Touch works just fine.

It's just the stylus that is not working.

I have no idea how or where to address this.

EDIT:
Apparently it's on my end only.
Stylus not working under any OS (UNIX-based, Dalvik-based or Windows).
Hopefully it's just a dead battery and not faulty hardware.
I'll test this once I get home with a fresh battery and report back.

**Comment by Sunburst0218** [comment] 2023-08-02 09:24
![BBA9110C-6A35-43CC-B46D-A95A3A8CD7ED](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/99610421/07725b97-e4e6-489d-b462-dc5d0d05ae13)
I may need to reinstall macOS 13, because the old EFI doesn't support macOS 14, and I found that I couldn't use the new dynamic wallpaper when I experienced the 14 system.

**Comment by billabongbruno** [comment] 2023-08-02 09:30
> ![BBA9110C-6A35-43CC-B46D-A95A3A8CD7ED](https://user-images.githubusercontent.com/99610421/257766625-07725b97-e4e6-489d-b462-dc5d0d05ae13.jpeg) I may need to reinstall macOS 13, because the old EFI doesn't support macOS 14, and I found that I couldn't use the new dynamic wallpaper when I experienced the 14 system.

I faced that issue when first trying to install macOS on another machine.

It was an easy fix.

Just make sure you have an SMBIOS for MacBookPro 15,2 or something like that.

I used to have MacBookPro 14,1 and that model has been dropped for macOS 14, so I got the exact same screen as you did.

Simply make sure you use a correct SMBIOS and you should be able to boot.

**Comment by Sunburst0218** [comment] 2023-08-02 10:05
Oh, no! I found that the old EFI doesn't support SD card

**Comment by balopez83** [comment] 2023-08-02 19:11
@billabongbruno @Sunburst0218 Copy this one into the 8.0.1 EFI and let me know if this works. 
[UTBMap-SP4.kext.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12243839/UTBMap-SP4.kext.zip)

**Comment by balopez83** [comment] 2023-08-02 19:12
I simply added the "missing" USB ports that were in the "old" USB mapping and placed them in the new map. This should activate all ports now and allow the SD card to work.

**Comment by billabongbruno** [comment] 2023-08-02 19:59
> @billabongbruno @Sunburst0218 Copy this one into the 8.0.1 EFI and let me know if this works. [UTBMap-SP4.kext.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/12243839/UTBMap-SP4.kext.zip)

Can confirm.

By mix-matching 8.0.1 ACPI and kexts, along with this patch, microSD card functionality is restored under Sonoma.

Thank you for the expedite fix.
I didn't have time to check if was simply a missing port (which it was), or else I could have addressed the issue, along with a proposed fix.
Sorry about that.

Thank you once more, @balopez83 .


EDIT 1:
I suppose you can now add to the list of supported features the fact this your repo supports the Surface Pro Dock.
Out of a bug, comes a feature.
lol

EDIT 2:
The stylus simply lacked a fresh battery.
All is working now.

**Comment by balopez83** [comment] 2023-10-11 00:12
Closing this ticket as resolved. This fix will be part of release version 9.0.0

**Closed as completed by balopez83** 2023-10-11 00:12 UTC
