### ISSUE TITLE
Big Sur installation problems

### ISSUE THREAD

**Issue by Broodierchip** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#9] opened 2023-04-21 04:05 UTC
I used the files to make an installer for my surface pro 4. Everything is fine up to the point of the installation where I pick the country as soon as I move the mouse or go down with the keyboard it crashes. What am I doing wrong?

**Comment by billabongbruno** [comment] 2023-04-21 06:10
> I used the files to make an installer for my surface pro 4. Everything is fine up to the point of the installation where I pick the country as soon as I move the mouse or go down with the keyboard it crashes. What am I doing wrong?

Hey there.

Which processor version of the SP4 do you have and what config.plist file are you loading?

**Comment by Broodierchip** [comment] 2023-04-22 04:24
Hi, thank you for reaching out. Sorry for taking a second to respond. My processor version is Intel (R) Core (TM) i7-665OU @ 2.20GHz. I was trying to do my install with the config.plist that was included.  I used GenSMBIOS to update the Mac Serial and Generate UUID, and Generate ROM.

**Comment by balopez83** [comment] 2023-04-24 16:55
Hi @Broodierchip I am looking into this right now. I believe the issue is that your graphics card is not being driven properly and in Big Sur or newer it causes issues like what you are experiencing. Please ensure that your config.plist you are using is for the i7 Surface Pro version and not the i5 or i3 Surface Pro or any of the Surface Book's. If you confirm that please try to use a vanilla i7 Surface Pro config.plist to rule out any errors in editing when you added your serial information. 

If that doesn't work can you try an older release version just so I can rule out a possible error when creating the config for the i7 surface pro 4

I am working on a new very big release and am working through some bugs with it. That said I am not entirely sure it will fix your issue unless I determine that the graphics settings are not set properly for your i7 surface pro 4. 

I have noticed that some users have had some issues with the Surface Keyboard. While most should work it seems some early models of the keyboard cause issues. You may also want to test a usb keyboard with the Surface Keyboard removed and see if that has the same issues. 

Can you also report back and let me know if it appears if you are getting graphics acceleration or if its choppy with graphics glitches?

**Comment by Broodierchip** [comment] 2023-04-25 01:04
Thank you for your detailed response. Helping me with something that was very basic. I was initially confused about the instructions about the config.plist because when I downloaded the files I downloaded the files from the man page on the project and not the revision section which has multiple config.plist. I have Big Sur installed. Now I'm just trying to get the wifi and touch screen. I looked in the quirk section of your guide about the touchpad to turn off the haptic feedback. I don't know if my touchpad is not talking to the computer fully because when I go the touchpad settings on the computer, my computer says that there is not a touchpad plugged into the computer. So, currently I can't edit any touchpad settings on my computer. Again thank you for all your help and my bad about not realizing that I needed to look for the files in the revision section and not just from the main page download.

**Comment by balopez83** [comment] 2023-04-25 05:35
@Broodierchip I am glad you were able to get graphics running and get it installed. The issue with the touchpad is either a usb issue or the BigSurface.kext isn't loading. Make sure you are using the Surface Pro config and not the Surface Book config. The USB mapping of the two devices are different and that might be the issue. I have just uploaded an entirely new EFI which I would recommend trying just make sure you use the config specifically designed for the Surface Pro i7. I have changed the graphics type though and can't test it but after some research it may work better than the previously selected one. If graphics slows way down and is not 'accelerated' with the new config let me know and I can push a quick update to fix it.

**Comment by Broodierchip** [comment] 2023-04-25 23:29
Ok, I will download the new update and try that out on my computer and I will let you know if I experience any issues with it. On the note of the touchpad, something that comes to my mind is the possibility that the touchpad is not responding because of the battery in the computer not being read correctly. I say that because I have taken apart and repaired Macbooks and noticed that the Mac would not let you customize the touchpad without the battery. It does not even recognize that there is a touchpad on the computer, maybe it is the battery, or like you said the files are not loaded correctly for the USB or BigSurface.kext. Also, quick question, in the guide for installing the wifi and Bluetooth drivers I have to put the Mac into recovery mode. I know how to do that on my Mac. But I seem to be having some difficulty with my surface pro. I have held various recovery mode button combinations and the only thing that ever loads is the screen where you can pick what drive you want the Mac to run.  So, my question would be how do you put into recovery mode?

**Comment by Broodierchip** [comment] 2023-04-26 01:27
Thank you for the update file. Just want to let you know that I have now tried the new file and the trackpad is working correctly. But now I can't adjust the display brightness at all. It seems to be locked at max.

**Comment by balopez83** [comment] 2023-04-26 02:28
@Broodierchip try this config.plist. I had to zip it due to limitations imposed by GitHub. Make sure to rename the file config.plist. Once you confirm it is working I will update the releases. I suspect your issue was due to the graphics not being accelerated like it was supposed to have been. 

[config-SurfacePro4-i7.plist.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/11328381/config-SurfacePro4-i7.plist.zip)

**Comment by Broodierchip** [comment] 2023-04-26 03:33
Sadly it seems that config.plist broke my build. Right now if I attempt to load my installed OS the computer will crash and it will reboot to the screen where you pick the drives. I thought I would try to install the OS all over again but the keyboard and the touch screen seemed to be unresponsive then it crashed again.

**Comment by balopez83** [comment] 2023-04-26 04:29
@Broodierchip well this is an annoying issue. Try the config below and see if that works. Keep in mind that the touch screen should not work on a clean install until you install the IPTS tool. Regarding your question about recovery, OpenCore works a bit different than a real mac. At the OS selection screen simply hit the space bar and it will give you the option to enter recovery, it also will expose a tool to change SIP at boot so you don't even need to enter Recovery. 

[config-SurfacePro4-i7.plist.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/11328983/config-SurfacePro4-i7.plist.zip)

**Comment by balopez83** [comment] 2023-04-26 05:16
@Broodierchip If that last config doesn't work I will have access to a Surface Pro 4 tomorrow which I can test on. Your issue is most certainly graphics related which is a bit confusing considering I originally tested that graphics configuration on an i7 Surface Pro 4 though perhaps something got messed up in the latest releases. 

Can you also let me know if the battery indicator was working when you used the last working config file (the one that you couldn't change the brightness with)?

**Comment by Broodierchip** [comment] 2023-04-26 12:10
I Just tried the last file
That you sent me and I just changed the SMBIOS. I then tried to boot and it is same as before just crashing. Thank you for telling me how to access recovery mode.

**Comment by Broodierchip** [comment] 2023-04-26 18:20
Forgot to respond to your question about the battery. When I was using the computer the battery indicator seemed to be working fine and that might be why the trackpad was working correctly.  I will also adds that I was not using the computer for a long amount of time, I will be more than glad to boot it up again with the last working config.plist file and monitor the battery and tell you if the battery indicator keeps working and how accurate it seems.

**Comment by balopez83** [comment] 2023-04-26 21:54
@Broodierchip I have resolved the issues you were experiencing with release 7.1.1 now posted in the releases section. I tested on a i7 Surface Pro 4 and verified it is fully working as expected. You should be able to complete a clean install with no issues though expect that touch won't work until you install the IPTS program. 

You should also use the "ToggleSIP" function to do a one time boot into macOS to install wifi drivers. You can get the "ToggleSIP" option by clicking the spacebar at the OS selection screen. This is the preferred method of toggling SIP on a Hackintosh rather than doing it through recovery. 

I am closing this issue but if you still have issues feel free to re-open.

**Closed as completed by balopez83** 2023-04-26 21:54 UTC

**Comment by Broodierchip** [comment] 2023-04-28 01:22
Thank you for the update file my computer works great now. I'm having issues with charging, my computer will say it's charging for one second then stop then start and it is not actually charging.Other then that everything works, trackpad, screen brightness and the wifi Bluetooth work. Well as as far the Bluetooth and wifi go I think it is working I have to get a USB lol.
