### ISSUE TITLE
Not an issue. Any solution for flickering / ghosting?

### ISSUE THREAD

**Issue by alappatsj** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#21] opened 2023-11-14 16:26 UTC
Thank You very much for EFI. Both SP3 & SP4 EFI working great, Thank You.

I also have SP4 Core i7 & 16 GB version but very frustrated with flickering / ghosting. On Windows, it used to work for 1 hour or more but on MacOS, it is early. Working fine of external display. But Unable to use touch or even just the display (without external). 
So is there any settings suggestion or tweaks for getting rid of flickering / Ghosting ?

**Comment by balopez83** [comment] 2023-11-14 17:11
@alappatsj That's a known issue with all SP4 devices. They produced two screens, one was made by LG I think, and suffered from delaminating cable connectors. When the device heats up the cables lose connection which causes screen flicker/ghosting. The only solution is to replace the entire screen and cable assembly. One solution was to use the SP5 screen and a cable adapter which is what Microsoft itself did in the final production of the SP4. 

If you choose to go down this route it's probable that the screen will break during removal which would be fine since you're replacing it but I would also recommend that you upgrade the battery and if you want also the drive if needed/wanted. At this point the battery is pretty old so it's only a matter of time before it starts to swell. Be extremely careful removing the battery as they used an extremely strong adhesive to hold the battery down and it is very likely to be damaged and catch fire if you are not careful. While others may disagree, I personally used "Goo Gone" and lightly applied under the battery and allowed it to soak into the adhesive. In order to remove the battery you have to remove the mainboard so there is far less risk to the circuits when applying adhesive remover. Combined with "iFixit's" supplies and instructions, I was able to remove the battery without severely damaging the battery. 

You should also know that when replacing the screen you need to remove and keep the circuit boards attached to the screen as you will be reattaching them to the new screen; order new stick-on antennas as they will likely be damaged when you remove the screen, and if you choose to go the SP5 screen option, you won't have the ability to use touch in macOS as the touch driver won't correctly work. Touch will work in Windows and Linux though with the SP5 screen. You can replace with another SP4 screen which will allow touch to work in macOS but it might suffer from the same screen flicker issue again someday in the future.

Some final notes; the touch circuit board grounds to the back of the screen. You need to make sure you don't use any non-conductive double sided tape or adhesive when attaching the board and you must ensure a good contact. If you fail to do this, you will only be able to use touch when holding the tablet as it will use you to ground the screen and computer enabling touch. I made this mistake and it was very frustrating because I had to remove the screen again. Keep in mind as well that there is a lot of heat in there so just cause it works when you test and before adhering the screen back on, the touch board can loosen if not secured properly. 

Hope that helps get your computer working again.

**Comment by alappatsj** [comment] 2023-11-18 18:33
Thank You very much for your detailed response. Sorry to respond you late.

As I am new to this hackintosh and especially with surface device, facing some issues. I bought a MDP to HDMI cable & connected to a LG HD TV. I am able to see the display but with ether greenish tint or purple tint. This issue is with Surface Pro 4.

And for Surface Pro 3, there is no colour issue, but very, very frequent disconnection. In other words, no proper connection.  

I would really appreciate if you could provide a solution for SP4. As the internal display is faulty, require external display desperately.  With VGA cable, there are no colour issues, but resolution issues. But for HDMI cable (Mini Display port to HDMI cable), there is Purple / green tint. Please help

**Comment by balopez83** [comment] 2023-11-18 18:55
@alappatsj are you using the latest EFI release? The green screen issue should have been resolved in the latest releases. That said some cheaper mDP to HDMI cables just don't work well and can cause issues displaying video properly. 

I am testing an upcoming release but using the same graphics settings at 10.0.3 and my mDP to HDMI is working properly so if you're using the latest release, I am unsure what your issue is.

**Comment by alappatsj** [comment] 2023-11-18 19:16
Thank You very much for your prompt response.
Sorry to ask you, how to update to latest version? 
IF I just download latest version & replace the new EFI, there can be issue with old Serial number & other things, right? I had generated / Edited old Config file with Serial Number, UUID etc.
So how we are supposed to copy those details to new / latest EFI release?

**Comment by alappatsj** [comment] 2023-11-18 19:51
I think, I am using your latest release. Most of the files are updated/modified on 7th Nov.
So the green tint may be because poor quality of HDMI cable. But it was not a cheap cable by the way. 
The OS is Sonoma. IF there is any more solution for this issue, please guide.

And it would be helpful for others also (like me who is new to these things), if you could put a note, how to update the existing EFI when you release new versions. 

And I think I broke the boot of SP3. I had edited the config.plist (to disable CSR), and on form the next boot, I am getting blank/black screen after loading/booting. It seems, EFI got corrupt (SPro3).

**Comment by balopez83** [comment] 2023-11-20 03:51
@alappatsj So even if the cable isn't cheap it can still have issues. I have four different mDP to HDMI adapter/cables and each one responds differently. One has a black screen despite being detected by macOS, the other flickers, and the last two work perfect. I suspect it has to do with the display port version compatibility since the computers are fairly old now. 

As for upgrading it is fairly easy. All you need to do is copy your SMBIOS information you generated to the new config and completely delete and replace the EFI folder with the new one after you copied the SMBIOS information. Unlike regular software there is no upgrade simply a delete and replace. The only time there is a difference is if I have to change the computer model to fix something or add features at which time I indicate that in the release information and state what is required to move to that version.

Lastly, there is no option to turn off CSR in the config file for OpenCore that I am aware of and you should never need to. As Is my SP3 release should give you the best support out of the gate and everything in all OS's should work with those releases. The only thing you should ever do when modifying the releases is add your specific SMBIOS serial information if you want to use iMessage or other iservices, otherwise you don't even need to make those changes. The only way I would recommend fixing your issue since I am not sure what you messed up in that release would be to simply delete the EFI and replace with a clean one from my releases which will get you up and running again. 

To caution you: if you have installed other OS's you do need to be careful and not delete their folders in the EFI folder. If you do you won't be able to boot them again. My releases only replace the Boot folder, grub folder,and OC folders. You must copy over any other folders to the new EFI folder if you have other OS's.

**Comment by alappatsj** [comment] 2023-11-20 10:43
I do really really appreciate your efforts to respond to everything in detail & in length, I do really appreciate it.

I somehow managed to boot into SP3 with a USB drive with backup EFI. As I checked, it was your latest release but I was using i7-noMDP config file as the other one had issues with graphics. The images & videos were not displaying in downloaded apps like chrome & brave browser etc. But native apps like Safari had no issues, was working very much fine. So I have used i7-noMDP config & most that's the reason HDMI didn't work on SP3. When I tried the other Config, HDMI was working properly. And BTW I am now using Windows on SP3 as I have Hackintosh on SP4. 

One thing is clear with SP3, the HDMI cable was ok, it was working with SP3 i5-MDP config. But for SP4, HDMI is loading images & videos & everything. But with purple/green tint. I have tried all the colour profiles, but still green/purple tine. The cable is MiniDisplay port to HDMI. Working fine with SP3 with MDP config plist. But the same cable giving green/purple tint for SP4. 

I saw one video in which they are copying RGB profile to System/libraries/Displays/ COntent.../Overrides. But I was unable to copy to that folder. Some comments were suggesting to disable SIP for sometimes. Thats what I was trying to mess with EFI. There is a value in Config file for CSR to disable/enable. As I opened EFI in Opencore configurator, there were some errors. I ignored it & went ahead to change the values for CSR, saved the file & rebooted. The result was blank/black screen after booting. 

Now the booting issue is fixed. But I am still looking for suggestion or solutions for HDMI to work in SP4. Your help will be greatly appreciated.

**Comment by balopez83** [comment] 2023-11-20 15:31
@alappatsj So you're doing too much to try to fix that issue. The issue you're experiencing comes down to two simple lines in the graphics properties section for your intel graphics chipset. I would highly recommend undoing all your changes to both the config and macOS as they will more likely cause issues. 

I'm not exactly sure why your system is having the green screen issue but I am sure I simply missed something in my last release. The issue occurs when an mDP port is not described properly and so macOS uses it wrong. 

Since my system is working I need to know more about yours. What cpu and memory configuration do you have? (E.g i7, 16gb)

**Comment by balopez83** [comment] 2023-11-20 16:43
@alappatsj Regarding your SP3 issue, I don't want to confuse others that might look at this issue here in the SP4 repo; so going forward please create a new issue in the SP3 repo and create new issues for any other unrelated issues you may have on the SP4. 

The SP3 i7 config no mDP is why your HDMI does not work. The mDP is the correct name for that port and that particular config does not have the fixes to allow use of an mDP to HDMI adapter. This was done to resolve issues where some i7 devices might not work with the fix. In my next SP3 release I do anticipate having that resolved but for now only the i5 config will work with mDP to HDMI adapters. When you experience flickering or other issues with graphics using the main i5 config it is an issue with how macOS is attaching its drivers and so graphics acceleration is not fully working. While it technically should work properly, I will need to do some more work to get everything working on the i7 devices. In the interim, if you would like to use your SP3 for macOS you will need to be patient for me to resolve the issues and get it running. For now, I am working with my limited time to resolve several key issues with the SP4/Book devices and issue a new release.

I will be changing the SMBIOS on the next release for both the SP4/book & SP3 repos so I wouldn't waste too much time generating or copying over your serial information as you will need to re-generate new data with the next release. I do anticipate the next SMBIOS change to be the last one I will ever do because of the new patches I have implemented.

**Comment by balopez83** [comment] 2023-11-20 17:46
@alappatsj One other quick thing. Using OpenCore configurator is very dangerous. Each version of the configurator works for only two versions of OpenCore, the release version as of the configurator release and the Dev version. If you are getting errors you are using the wrong version for the version of OpenCore in that EFI, specifically, I believe it is OpenCore version 0.9.5 where the latest version is for 0.9.6. Using the wrong configurator on the wrong release will break your build, often irreparably. You should always use ProperTree for the best results editing a config. 

As a general rule you should never edit anything in these configs unless you know how to fix something. These configs baring my making a mistake on a release should be working better than any other release you may find on the web at this point and changing settings will break things. Other than adding serial information it's best to just ask me if you think something is wrong rather than just changing things randomly. I'm happy to help but it's difficult to help if you change things as I will always assume you are starting with an unchanged release and can't support it without knowing what changes have been made. Also surface devices are really picky so changing settings likely will make it so you can't boot. 

I looked over the SP4 latest release and I am actually confused as to why you are seeing a green filter on it. My guess is more testing will be needed. I suspect that either the graphics spoof will need to be adjusted or the graphics ports need to be mapped differently and so I await your response in your models specs so I can make appropriate adjustments.

**Comment by balopez83** [comment] 2023-11-20 17:49
@alappatsj sorry I just re read through the comments and saw your specs. I have an i7 model and can test it. Give me some time as I will prob just try to issue a new release sans a few of my fixes I am working on in an attempt to get it working.

It may take a couple days to resolve the issues but rest assured I am working on it.

**Comment by balopez83** [comment] 2023-11-22 11:17
@alappatsj I have posted a pre-release version 11.0.0 that should resolve your issues with external monitors. Please test and let me know if you experience any issues. I haven't finished fully testing this release so there may be some other bugs though it seemed to work well so far on my i7 SP4. You will need to re-generate your SMBIOS serial information as an SMBIOS change was required to resolve several other lingering issues. I do not anticipate changing the SMBIOS in the future and so in the future you will only need to copy it into future config.plist files when replacing the EFI during upgrades. 

If this release resolves this issue please let me know and go ahead and close the issue.

**Comment by balopez83** [comment] 2023-11-24 21:11
Closing this issue as this should now be resolved with release 11.0.0 and newer. Please reopen if the issue is still not resolved.

**Closed as completed by balopez83** 2023-11-24 21:11 UTC

**Comment by alappatsj** [comment] 2023-12-04 06:29
Extremely Sorry to respond to you late.

And I do really, really, really appreciate your efforts to write such a long detailed response. Many people, especially highly qualified people like you might not have spend time to write very detailed response. Thank You very much. I have tried your latest EFI, it is working great. No glitches or no crashes. Just working as fine as normal or original Macbook.

The issue I am facing is related to this Model (Surface Pro 4). Unbearable level of Flickering & Ghosting. When it was on Windows, we used get 1 to 2 hours without flickering. When the device gets hot (after 1 or 2 hours), then the flickering issues starts. But in MacOS, this issues starts very very early. And even if we shut it down for a couple of hours, still flickering may start rom the boot.

I have a serious doubt, Fan might not be working. In your list of working features, you have mentioned, Fan Working fine. Are you sure about it? or my device (Fan) is physically damaged (not working) ? I have tried a couple of apps, but none of them detected Fan in my system, Even the Fan Control App in MacOS(Mac OS Fan Control App).

I would really appreciate if you could please help me on this, to understand whether it is physically damaged or any software glitches.

**Comment by balopez83** [comment] 2023-12-04 17:13
@alappatsj yes, I can confirm that the fan is working and with the Surface devices is almost completely controlled by the UEFI and is not controllable by macOS. 

Most software you would get that is supposed to control/view fan speed won't work on a hackintosh as those programs are expecting a specific type of hardware that no hackintosh would have. As such there is no known software that will let you control or view fan speeds. Additionally, Surface devices have very proprietary hardware that is difficult to access which is one of the reasons it took about 7 years before anyone was able to even get the touch screen, Pen, and Battery status working on SP4 and newer devices. 

The issue you are experiencing is related to heat in that macOS does use different CPU scaling methods than Windows would. I suspect but cannot confirm that Windows does have the ability to drive the fan at lower temperatures which may result in a cooler computer though again I cannot confirm. Regardless this does not mean that running macOS would raise the temperature of a hackintosh to an unsafe level. The fan always kicks in before the computer gets anywhere close to an unsafe temperature.

You can confirm if your fan is broken by simply plugging in the computer and then running the new video screensavers for 5 min. If you are not on macOS Sonoma use the Aerial screensaver which can be downloaded from the web after a google search. This will cause enough demand on the CPU to make the fan turn on. 

With all of that being said, your screen is dying, and it is driven by the delamination of your screen from the cables. It will get worse unfortunately and the only real solution is to replace the screen. While heat causes the issue, it does not necessarily go away just because the screen cools. That is how it starts but eventually the delamination gets so bad that it will happen despite being cool. Replacing the screen will solve the problem for good. You can see how widespread of an issue it was that a website was made to appeal to Microsoft to fix all of the bad screens here: https://flickergate.com/ . Note that the last "Update" on that page has a typo and should have said that it cannot be fixed with a software or firmware update. The only way Microsoft fixed it was to replace the computer with a late model SP4 that contained a new screen. The new screen was the one they used for the SP5 and did not suffer from the delamination issue.
