### ISSUE TITLE
surface pro 4 minidp ports doesn't work

### ISSUE THREAD

**Issue by ZuoAoyu** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#16] opened 2023-08-29 07:13 UTC
First of all, thank you for your hard work!

I recently tried to connect my computer to a monitor through the minidp port, but I found that it didn't work. 

Once before, the external monitor could display the picture normally, but the color was greenish. However, in recent times, no matter how I plugged in or unplugged the minidp cable, the external display could not be lit up.

**Comment by balopez83** [comment] 2023-08-30 16:12
Can you let me know what "Release" used to work for you for mDP out? It was my understanding it was working however its possible that some of the recent changes caused new issues. 

Also; what are your computer specs and which config are you using. I have two different graphics chipsets being supported with this release but one of them may not actually support mDP out. Additionally is your mDP out converting to Full size DP, HDMI, or other?

**Comment by ZuoAoyu** [comment] 2023-08-31 03:40
@balopez83 Thank you for your reply. My surface is _Surface Pro 4 i5 8 + 256_, macOS version is 13.2, and the current efi version is 8.0.1. The cable I used is minidp to hdmi.

**Comment by balopez83** [comment] 2023-08-31 04:09
@ZuoAoyu Thank you for providing that. Can you also tell me what release you used that resulted in working mDP with the green shading?

**Comment by ZuoAoyu** [comment] 2023-08-31 05:50
@balopez83 Sorry, I can't remember the exact version number. It might be 6.2.X or 7.1.X.

**Comment by balopez83** [comment] 2023-09-12 23:09
@ZuoAoyu Sorry for the delay getting back to you on this. I am pretty sure I know what the issue is though it may require some testing. I have been unfortunately really busy lately so haven't been able to look into this. I'll try to get a revised config.plist to you to test soon to see if it resolves the issue. I intend to release a new EFI soon anyway so it would be good to get this fix in there too.

**Comment by ZuoAoyu** [comment] 2023-09-13 12:09
Thank you for your hard work! @balopez83

**Comment by balopez83** [comment] 2023-10-12 06:31
@ZuoAoyu wanted to let you know that I have resolved this issue and it will be released with my next release version 9.0.0. This is a big update and unfortunately required another SMBIOS change to resolve several issues. I should have the next release posted within the next 24 hours.

**Closed as completed by balopez83** 2023-10-12 06:31 UTC

**Comment by ZuoAoyu** [comment] 2023-10-23 01:47
> @ZuoAoyu wanted to let you know that I have resolved this issue and it will be released with my next release version 9.0.0. This is a big update and unfortunately required another SMBIOS change to resolve several issues. I should have the next release posted within the next 24 hours.

Nice work!
