### ISSUE TITLE
Black screen / reboot issue on Installation / Post-Installation on Ventura Final (MacOS 13.0)

### ISSUE THREAD

**Issue by billabongbruno** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#6] opened 2022-11-01 09:05 UTC
Hey there, once again.
How are you?

Just wanted you to know this is isn't a function-breaking bug, it's just midly annoying, at worst.

So, let me see if I can describe it in the best way I can.

Under the SP i5 build, by using the boot-args you selected "lilucpu=9 keepsyms=1 debug=0x100 -lilubetaall -wegnoegpu", I can only install Ventura if I manually reboot, as everytime the installer completes a step and tries to trigger a reboot, it fails and all that it produces is a black screen (slightly backlit - and the keyboard lights up as well if I press it, so it's definetely on), therefore leading me to force shutdown and pick up from where it left off, upon a manually forced triggered shutdown and boot up.

Same thing goes for when it's installed.

HOWEVER, if I remove the "keepsyms=1" argument (I know that it's companion to debug=0x100, but I tried them one by one), then it reboots just fine and yields no black screen whatsoever (on reboot or shutdown), but it always produces the annoying error message on boot of "Your computer has restarted because of a problem, bla, bla, bla, wait for a few seconds or press a key, bla, bla", then leading to the possibility of sending Apple a report (which I can upload here if you want, in case my explanation wasn't clear) and always references a kernel failure and mentions the boot-args.

I have experimented with boot-args quite a bit and have added and remove different arguments to see if it would make a difference. It didn't.
I have tried clearing NVRAM, to see if the error was stuck there.
It wasn't.
It's perfectly functional, it's just mildly annoying to have to see that error message everytime and and then having to press once to boot (or wait) and then having to click "Ignore" everytime the report suggestion comes up and then again click "Open" (or wait 60 seconds) to open MacOS.

I should note that this issue DIDN'T occur as much (it was hit and miss) when I had "showpicker" set to "true".
Having it set to "false", however, triggers this everytime.

I am using OC 0.8.5 on my SP4 i5 with Ventura 13.0.

I know it's not a Ventura nor a OC issue, as my other computer (the ACER NITRO 5) boots up just fine.

And on that note, I have figured out how to consistely get Intel BT working on Monterey and Ventura (on the other computer).
I know you were also interested in this, so just let me know if you still need it.

Thank you again for all your work.

Best regards,

**Comment by balopez83** [comment] 2022-11-01 20:47
Hi @billabongbruno , thank you for bringing this to my attention. I haven't yet installed Ventura but am doing it now. Once installed I will figure out if I can duplicate the issue you are experiencing. 

At first impression I believe the boot-args are not actually the issue despite the differences in your experience after removing "keepsyms=1". Those boot args only increase the logging and prevent auto reboot on kernel panic. By removing the boot args its simply allowing the computer to reboot automatically without forcing the power off. 

If you can send me the logs generated from the KP it would be helpful especially if I don't have the same issues on my end. I suspect I already know where the issue could be but will have to get back to you once my install completes. I do have a slightly updated EFI that I am planning to release once OC 0.8.6 drops but if it resolves Ventura issues I may go ahead and release it early. 

I am definitely interested in the bluetooth issue as I have not had any time to figure it out on my 11th gen computer.

**Comment by billabongbruno** [comment] 2022-11-01 23:21
Hey, @balopez83 .
You're welcome, of course.
I didn't mean to bother at all, just wanted you to know.

I am aware that the boot-arg itself isn't the issue, I was just putting out as much information as I could.
As per your request, I am attaching the log file in .txt format (I copy-pasted into a .txt file).

A very important piece of information that I forgot to mention regarding the SP4 under Ventura:
Even if I trigger a SHUTDOWN in macOS, it always REBOOTS my SP4.
It never shuts it down.
It's super weird.

As per the Intel Bluetooth issue, I am also attaching the Nitro 5 config.plist so you can have a look, but basically these are the steps taken:

1 - Get the 2.2.0 version of Airportitlwm.kext (the Alpha version, not the latest stable release, that's 2.1.0) for the correct macOS version (I'm using Ventura) here: https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0-alpha

2 - Get the latest IntelBluetoothFirmware.kext and IntelBTPatcher.kext here:
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/download/v2.2.0/IntelBluetooth-v2.2.0.zip

3 - Get the latest BlueToolFixUp.kext from here:
https://github.com/acidanthera/BrcmPatchRAM/releases/download/2.6.4/BrcmPatchRAM-2.6.4-RELEASE.zip

4 - Make sure to load things in this order in your config.plist:
Lilu --> VirtualSMC --> Airportitlwm --> IntelBTPatcher --> IntelBluetoothFirmware --> BlueToolFixUp

5 - Reset NVRAM

6 - Force shutdown your PC (hold power button for at least 30 seconds)

7 - Boot into macOS and make sure to force your Wifi to connect to a 5GHz network (the Alpha version takes a while to scan for networks. Either wait or manually input your Wifi settings - SSID, Protocol and Password)

8 - If Bluetooth is still not available, do the following:
Open the terminal and type "sudo pkill bluetoothd";
Go to macOS system settings and enable Bluetooth from there (toggle the switch);
If you still can't toggle the switch, run the "sudo pkill bluetoothd" command again until you can;
Wait for about two minutes;
Reboot normally

9 - Bluetooth should be working with no issues from now on, even after a warm or cold boot or reboot.
If not try shutting down your PC normally via macOS shutdown button and then holding the power button for 30 seconds before booting it up.

FYI, as a reference, I am using MacBookPro15,2 in my config.plist (which I am attaching anyway)

This is the only way I got it working for me.
Fingers crossed it works for you too.

[Intel_Bluetooh_Ventura_config.txt](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/9914618/Intel_Bluetooh_Ventura_config.txt)
[macOS_Ventura_log.txt](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/9914619/macOS_Ventura_log.txt)

**Comment by balopez83** [comment] 2022-11-01 23:50
Thanks for sending the Bluetooth information. I will try that with my system once I have some time. 

So the issue with your KP's is the BigSurface.kext, I will see if the 6.3 version has better compatibility but its not noted that Ventura is supported officially yet. I believe I remember this being an issue for a while but wasn't going to be resolved until ventura was officially released. 

https://github.com/Xiashangning/BigSurface/issues/48

**Comment by balopez83** [comment] 2022-11-01 23:52
If you don't mind the KP's, you can stick with it or disable the BigSurface.kext until a new one is released. Personally, I would go back to Monterey until Ventura is officially supported.

**Comment by billabongbruno** [comment] 2022-11-01 23:54
> Thanks for sending the Bluetooth information. I will try that with my system once I have some time.
> 
> So the issue with your KP's is the BigSurface.kext, I will see if the 6.3 version has better compatibility but its not noted that Ventura is supported officially yet. I believe I remember this being an issue for a while but wasn't going to be resolved until ventura was officially released.
> 
> [Xiashangning/BigSurface#48](https://github.com/Xiashangning/BigSurface/issues/48)

Oh, I am already using version 6.3 of BigSurface.kext.

I forgot to mention that.

**Comment by billabongbruno** [comment] 2022-11-01 23:54
> If you don't mind the KP's, you can stick with it or disable the BigSurface.kext until a new one is released. Personally, I would go back to Monterey until Ventura is officially supported.

I'll just stick with it, for the time being.

I'll close the issue then, seeing as it's not related to your great work.

**Comment by balopez83** [comment] 2022-11-02 00:10
@billabongbruno , for now I actually want to reopen this in case anyone else has the same issue they will know whats going on. I just reviewed the issue on the Bigsurface repository and it looks like the issue is with the surface type cover. Can you reboot without the type cover and let me know if it causes the KP still? I am not using the SP4 right now so am testing with the Surface Book. Depending on what happens I may have you try a modded kext for me if the BS kext isn't updated soon.

**Comment by billabongbruno** [comment] 2022-11-02 00:17
> @billabongbruno , for now I actually want to reopen this in case anyone else has the same issue they will know whats going on. I just reviewed the issue on the Bigsurface repository and it looks like the issue is with the surface type cover. Can you reboot without the type cover and let me know if it causes the KP still? I am not using the SP4 right now so am testing with the Surface Book. Depending on what happens I may have you try a modded kext for me if the BS kext isn't updated soon.

I see.
Very well, then, let's leave it open. lol

So....
You were right.
I did exactly what you told me to and got NO Kernel Panic whatsoever.
Rebooted without the Type Cover and produced no errors.
Even the SHUTDOWN command worked.

I am always available to debug for you, of course.

Hopefully Xiashangning updates BigSurface soon.
If not, just let me know what I can do to help.

**Comment by balopez83** [comment] 2023-02-09 00:51
I have added fixes to the BigSurface code which fixes this issue. I will be issuing a new release including my BigSurface-custom.kext fixing this issue shortly as soon as I upgrade the EFI to the latest OC release and update any other relevant kexts. 

Since this is will now be considered fixed I am going to close this issue. If there is still an issue with reboot/shutdown after I issue the next release feel free to reopen it.

**Closed as completed by balopez83** 2023-02-09 00:51 UTC
